### ISSUE TITLE
Code seems correct but won't let me pass test

### ISSUE THREAD

**Issue by tbd007** [freeCodeCamp/testable-projects-fcc#1014]
https://codepen.io/TBD007/pen/abzvvpv

#### Issue Description

Although my code is exactly the same as the sample project that passes all tests it constantly  shows me these 2 errors.

3. The first element within each .main-section should be a <header> element which contains text that describes the topic of that section.
Not all elements with the class 'main-section' have a <header> element as a first element child : expected 13 to equal 14
AssertionError: Not all elements with the class 'main-section' have a <header> element as a first element child : expected 13 to equal 14
    at Proxy.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1881)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.strictEqual (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:655)
    at t (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:152697)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:154613)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35224)
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35154)
    at T.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41723)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42605
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41019)
4. Each <section> element with the class of "main-section" should also have an id comprised of the <header> innerText contained within it, with underscores in place of spaces. The id may include special characters if there are special characters in the respective <header> innerText. (e.g. The <section> that contains the header, "JavaScript & Java", should have a corresponding id="JavaScript_&_Java").
Not all elements with the class 'main-section' have a <header> element as a first element child : expected 13 to equal 14
AssertionError: Not all elements with the class 'main-section' have a <header> element as a first element child : expected 13 to equal 14
    at Proxy.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1881)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.strictEqual (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:655)
    at t (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:152697)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:155308)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35224)
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35154)
    at T.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41723)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42605
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41019)

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

https://codepen.io/TBD007/pen/abzvvpv

```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
