### ISSUE TITLE
Build a Tribute Page - User Story #5 Error?

### ISSUE THREAD

**Issue by fheinent** [freeCodeCamp/testable-projects-fcc#1106]
#### Issue Description

When the tests are run, #5 seems to fail because the code requirements are met and the popup claims the following:
"expected null to not equal null
AssertionError: expected null to not equal null
    at Proxy.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1889)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isNotNull (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1549)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:124317)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160"

The tested code reads as follows:
<div id="img-div">
            <img id="image" src="https://media.salon.com/2018/08/jean-luc-picard.jpg" alt="Jean-Luc Picard staring boldly to his foe">
            <figcaption id="img_caption">
                Captain Jean-Luc Picard sitting at his captain chair aboard the USS Enterprise
            </figcaption>
        </div>

I might be wrong but in that code I used a figcaption element with the id="img_caption", all inside the "img_div".

Thank you!

#### Browser Information

- Browser Name, Version: Google Chrome Version 80.0.3987.163 (Build oficial) (64 bits)
- Operating System: macOS Catalina 10.15.4
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```



```

#### Screenshot

<img width="1430" alt="Captura de pantalla 2020-04-22 a las 19 33 48" src="https://user-images.githubusercontent.com/26100265/80014173-324a1000-84d0-11ea-828c-1b319a67ab73.png">

**Comment by tbushman** [comment]
@fheinent please use the `id="img-caption"` instead of `id="img_caption"` and that should clear the error. Thank you.
