### ISSUE TITLE
Test issues with 'Responsive Web Design Projects - Build a Product Landing Page"

### ISSUE THREAD

**Issue by 8ie** [freeCodeCamp/testable-projects-fcc#1116]
#### Issue Description

Could you please educate me on how these projects are graded? Are we suppose to simply comply with the user stories, which was the case with the first two projects. Or are we suppose to comply with new instructions that are delivered via the test results after we have followed the user stories (hence, it is an inefficient process)?

To add greater clarity, the survey form tests don't match the required user stories for this particular project. I am receiving failures for my product landing page test results due to omissions that were not covered by the user stories.

I adjusted my product page to include some of these extra omissions that were easy to add, however, some are nowhere near the content of the user stories. 

Below are omission examples that I complied with because they were simple.
  
#Content
1. I can see a title with id="title" in H1 sized text.
2. I can see a short explanation with id="description" in P sized text.
3. I can see a <form> with id="survey-form".
etc.

However, below are other omission examples that I am questioning since they are nowhere near the user stories.

12. Inside the form element, I can select an option from a dropdown that has corresponding id="dropdown".'

13. Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute. Each radio button must have a value attribute.

etc.

I would greatly appreciate some clarity.

thanks

Every time I test the results.

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Dell Inspiron laptop

#### Your Code / Link to Your Pen

```
https://codepen.io/freeCodeCamp/pen/MJjpwO


```

#### Screenshot

Survey Form tests
passes:12 failures:5 duration:0.02
#Technology Stack
1. You can use HTML, JavaScript, and CSS to complete this project. Plain CSS is recommended because that is what the lessons have covered so far and you should get some practice with plain CSS. You can use Bootstrap or SASS if you choose. Additional technologies (just for example jQuery, React, Angular, or Vue) are not recommended for this project, and using them is at your own risk. Other projects will give you a chance to work with different technology stacks like React. We will accept and try to fix all issue reports that use the suggested technology stack for this project. Happy coding!
#Content
1. I can see a title with id="title" in H1 sized text.
2. I can see a short explanation with id="description" in P sized text.
3. I can see a <form> with id="survey-form".
4. Inside the form element, I am required to enter my name in a field with id="name". If I do not enter a name I will see an HTML5 validation error.
5. Inside the form element, I am required to enter an email in a field with id="email". If I do not enter an email I will see an HTML5 validation error.
6. If I enter an email that is not formatted correctly, I will see an HTML5 validation error.
7. Inside the form, I can enter a number in a field with id="number".
8. If I enter non-numbers in the number input, I will see an HTML5 validation error.
9. If I enter numbers outside the range of the number input, I will see an HTML5 validation error.'
10. For the name, email, and number input fields inside the form I can see corresponding labels that describe the purpose of each field with the following ids: id="name-label", id="email-label", and id="number-label".
#name-label is not defined : expected null to not equal null
AssertionError: #name-label is not defined : expected null to not equal null
    at Proxy.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1889)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isNotNull (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1549)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:134907)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
11. For the name, email, and number input fields, I can see placeholder text that gives me a description or instructions for each field.'
12. Inside the form element, I can select an option from a dropdown that has corresponding id="dropdown".'
Cannot read property 'tagName' of null
TypeError: Cannot read property 'tagName' of null
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:137269)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41222)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41976
    at f (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:593:1314)
var e=document.getElementById("dropdown"),t=null;"DATALIST"===e.tagName&&(t=e.previousElementSibling.getAttribute("list"),o.assert.strictEqual(t,"dropdown","When using the datalist tag, the accompanying input tag must contain a name attribute matching the datalist id.")),o.assert.isNotNull(e,'There should be a select field with id="dropdown" '),o.assert.isAtLeast(document.querySelectorAll("#dropdown option:not([disabled])").length,2,"Select should contain at least 2 selectable options "),o.assert.isAbove(document.querySelectorAll("#survey-form #dropdown").length,0,'The select field with id="dropdown" is not inside the form element ')
13. Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute. Each radio button must have a value attribute.
There should be at least 2 radio buttons : expected 0 to be at least 2
AssertionError: There should be at least 2 radio buttons : expected 0 to be at least 2
    at Proxy.p (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:3833)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isAtLeast (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1030)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:138165)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
var e,t=[].slice.call(document.querySelectorAll('input[type="radio"]'));for(var r in o.assert.isAtLeast(t.length,2,"There should be at least 2 radio buttons "),o.assert.isAtLeast(document.querySelectorAll('#survey-form input[type="radio"]').length,2,"There should be at least 2 radio buttons inside the #survey-form "),o.assert.strictEqual(t.length,document.querySelectorAll('input[value][type="radio"]:not([value=""])').length,"All your radio-buttons must have a value attribute "),o.assert.strictEqual(t.length,document.querySelectorAll('input[name][type="radio"]:not([name=""])').length,"All your radio-buttons need a name attribute "),e=t.reduce((function(e,t){return e.hasOwnProperty(t.name)?e[t.name]++:e[t.name]=1,e}),{}))Object.prototype.hasOwnProperty.call(e,r)&&(console.log(e[r]),o.assert.isAtLeast(e[r],2,"Every radio-button group should have at least 2 radio buttons "))
14. Inside the form element, I can select several fields from a series of checkboxes, each of which must have a value attribute.
There should be at least 2 checkboxes inside the form : expected 0 to be at least 2
AssertionError: There should be at least 2 checkboxes inside the form : expected 0 to be at least 2
    at Proxy.p (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:3833)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isAtLeast (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1030)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:139187)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
15. Inside the form element, I am presented with a <textarea> at the end for additional comments.'
There should be at least 1 <textarea> : expected 0 to be at least 1
AssertionError: There should be at least 1 <textarea> : expected 0 to be at least 1
    at Proxy.p (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:3833)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isAtLeast (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1030)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:139622)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
16. Inside the form element, I am presented with a button with id="submit" to submit all my inputs.

**Comment by Sky020** [comment]
Hello there.

It appears you are referencing two different Projects. This is the [Survey Form Instruction Page](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-survey-form):
If you go there, you will see all user stories.

Also, I notice your title has to do with the [Product Landing Page](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page). Just select the correct Test Suite for the project on CodePen.

Also, the link you posted is for the freeCodeCamp boilerplate, not your project.

I am closing this issue. Feel free to comment, if you have any more concerns.

**Comment by 8ie** [comment]
thanks!
