### ISSUE TITLE
Uncaught SyntaxError being thrown in JavaScript Calculator Test No. 13

### ISSUE THREAD

**Issue by dvbsknd** [freeCodeCamp/testable-projects-fcc#1191]
#### Issue Description

This could be as a result of an error in my code, but the test is throwing an actual error rather than failing. 

The test is:

> 13. If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign.

The calculator/code is behaving in a way that should result in that test passing, but it fails with an error.

The error is:

```
Uncaught SyntaxError: Unexpected token ';' (http://localhost:3000/calculator/index.html:3)
Error: Uncaught SyntaxError: Unexpected token ';' (http://localhost:3000/calculator/index.html:3)
    at a.onerror (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:593:1177)
    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:231:18)
    at invokeGuardedCallback (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:286:33)
    at invokeGuardedCallbackAndCatchFirstError (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:300:27)
    at executeDispatch (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:383:5)
    at executeDispatchesInOrder (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:408:7)
    at executeDispatchesAndRelease (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:3401:7)
    at executeDispatchesAndReleaseTopLevel (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:3410:12)
    at forEachAccumulated (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:3382:10)
    at runEventsInBatch (https://unpkg.com/react-dom@16.13.1/umd/react-dom.development.js:3427:5)

```

#### Browser Information

- Browser Name, Version: Version 83.0.4103.116 (Official Build) (64-bit)
- Operating System: MacOS Catalina 10.15.5
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Code for the project solution can be viewed [here](https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/tree/master/challenges/calculator).

#### Screenshot

![image](https://user-images.githubusercontent.com/1005395/87728537-99910b00-c806-11ea-97c1-cf6cfa41da6a.png)
![image](https://user-images.githubusercontent.com/1005395/87728547-a150af80-c806-11ea-9676-dc195599feff.png)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
