### ISSUE TITLE
Personal Portfolio Project - window.scroll is not a function

### ISSUE THREAD

**Issue by mertindervish** [freeCodeCamp/testable-projects-fcc#164]
#### Issue Description

Can't pass 2 unit tests because of the following error:

```
TypeError: window.scroll is not a function
    at n.<anonymous> (https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/479a98b1fe26160c9532ca1d734032bc16fe657c/build/bundle.js:20146:17)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559)
```

#### Browser Information

* Browser Name, Version: Google Chrome, 60.0.3112.101
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/mertindervish/project/editor/XrNJJx

#### Screenshot

![Screenshot](https://user-images.githubusercontent.com/7361642/29497024-a05cc7ca-85e8-11e7-8300-20c0f05268b3.jpg)

**Comment by mertindervish** [comment]
It was my fault. I had scroll variable in global context :smile:
