### ISSUE TITLE
at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:978)

### ISSUE THREAD

**Issue by bstrother1** [freeCodeCamp/testable-projects-fcc#317]
#### Issue Description

My Portfolio test keeps producing the error at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:978). My codepen is https://codepen.io/orangejuice300/pen/xzGzaB and despite removing the scripts I had imported in my HTML document I am still getting this error. It is good to also note my navbar does work and follows along the page. 

#### Browser Information

CodePen.
* Browser Name, Version: Chrome version 66.0.3359.181
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/orangejuice300/pen/xzGzaB
 
 
```

#### Screenshot

![error](https://user-images.githubusercontent.com/19878907/40821011-16a77e74-6532-11e8-97d5-4e2140535cd8.JPG)

**Comment by tbushman** [comment]
@bstrother1 When I test your codepen in Chrome Version 66.0.3359.181, it passes all the tests. Will you let us know if you continue to see this error?

**Comment by tchaffee** [comment]
Closing due to inactivity. If this is still happening please let us know and we will happily reopen the issue and try to fix it.

**Comment by tbushman** [comment]
The Travis build is failing on the Portfolio tests, so reopening in case this is related.

**Comment by tchaffee** [comment]
@tbushman I think we've now determined that the Travis build failure was something else? Can this be closed now?
