### ISSUE TITLE
Error on: Tribute Page #Layout 1. 

### ISSUE THREAD

**Issue by annakuchina** [freeCodeCamp/testable-projects-fcc#363]
#### Issue Description
So the error reads:

1. The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size. 
AssertionError: Try using the "max-width" style property : expected 'none' to not equal 'none'
    at Function.assert.notStrictEqual (https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/59cd8776401eb5f921f4663952b09974ef4d092d/build/bundle.js:17655:37)
    at n.<anonymous> (https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/59cd8776401eb5f921f4663952b09974ef4d092d/build/bundle.js:21194:23)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855

This issue happens when I run the tests on my webpage (<script src="https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js"></script> ) , responsiveness on my page works correctly otherwise.

#### Browser Information
Browser Name, Version: Google Chrome, Version 67.0.3396.87 (64-bit)
Operating System: Windows 10
Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/annakuchina/full/XYMMyZ/
 

#### Screenshot
![image](https://user-images.githubusercontent.com/38858199/41346248-4d18dd06-6f49-11e8-84c1-acc308d2062c.PNG)

**Comment by tbushman** [comment]
The tests pass if you add the css: `display: block;` to the `<img>` element. This requirement is mentioned in an assertion error message in our tests. Please reopen this issue if that doesn't work. Thanks!
