### ISSUE TITLE
Build a product landing page- nav link button in nav element. 

### ISSUE THREAD

**Issue by rfilaxwy** [freeCodeCamp/testable-projects-fcc#379]
#### Issue Description

When i run test on my codepen for product landing page. 

#### Browser Information

Codepen.io                      https://codepen.io/rfilaxwy/pen/VdMbMd?editors=1100
* Browser Name, Version: Chrome
* Operating System:  Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/rfilaxwy/pen/VdMbMd?editors=1100
 
```

#### Screenshot

5. When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.' AssertionError: The .nav-link with href="#contact" is not linked to a corresponding element on the page : expected null to not equal null
    at Function.assert.isNotNull (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17889:37)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21594:25
    at NodeList.forEach (<anonymous>)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21590:19)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000

**Comment by tbushman** [comment]
Hello @rfilaxwy . The section with `id="contact"` is missing. The page should scroll to that section when the anchor with `href="#contact"` is clicked.

**Comment by SalumJSUlomi** [comment]
When I click my links navigate as well, but the problem still there. what to do guys?
