### ISSUE TITLE
Error with Test #5 of Tribute Page project

### ISSUE THREAD

**Issue by jesselangdon** [freeCodeCamp/testable-projects-fcc#395]
#### Issue Description
I am attempting to pass all of the tests for the "Build a Tribute Page" project, but I'm unable to pass Test #5 "Within the "img-div" element, I should see an element with a corresponding id="img-caption" that contains textual content describing the image shown in "img-div".

```
AssertionError: Element does not have any content : expected 0 to be above 0
    at Function.assert.isAbove (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17717:36)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21168:23)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
```

I've tried several variations of code with the intention of passing this test, but nothing seems to work.

#### Browser Information

* Browser Name, Version:  Chrome 67
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

[https://codepen.io/jesselangdon/pen/jKzjaj](https://codepen.io/jesselangdon/pen/jKzjaj)
``` 
<figure id="img-div">
      <img id="image" src="https://res.cloudinary.com/jesselangdon/image/upload/v1529615499/jane_reach_out.jpg" alt="Jane reaching out to baby chimp">
      <figcaption id="img-caption">Jane and baby Flint in Gombe Stream Game Reserve, Tanzania. Photograph by Hugo van Lawick, 1965.
      </figcaption>
</figure>
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/2524993/41862441-c3d6d39a-7858-11e8-8b4b-d70489ecb2b5.png)

**Comment by jesselangdon** [comment]
Nevermind, I had two divs with id="imp-caption".
