### ISSUE TITLE
Image responsiveness not recognised by the testing app

### ISSUE THREAD

**Issue by casee8** [freeCodeCamp/testable-projects-fcc#499]
#### Issue Description

I'm using "jumbotron" class from bootstrap and the picture is 100% wide and it's responsive but I can't pass the test.

"1. The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size. AssertionError: Use the "display" style property with a value of "block" forresponsive images.: expected 'inline' to equal 'block'
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:147:295397)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559)"

#### Browser Information

* Browser Name, Version: Google Chrome, Version 67.0.3396.99 (Official Build) (32-bit)
* Operating System: Windows 10 32bit - latest
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/casee8/pen/EKjJLM

**Comment by tbushman** [comment]
@casee8 We're working on making error reporting easier to read. The error says to add `display: block;' to your `<img>` css. That passes the tests for you.

**Comment by Marie-Carrere** [comment]
@tbushman Hi ! 
I have the same exact issue, I can't pass the US n°8, though my image is responsive.
Plus, I added `display: block;` to my css. 

https://codepen.io/Marie_cm/full/YjaVLj/

Thanks for your help 😀
