### ISSUE TITLE
Inconsistent text results between localhost, Codepen and gh-pages

### ISSUE THREAD

**Issue by GK-Hynes** [freeCodeCamp/testable-projects-fcc#691]
#### Issue Description
I'm getting inconsistent test results when running the tests locally, on Codepen and on gh-pages

#### Browser Information
* Browser Name, Version: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
* Operating System: Windows 10 Home 1803
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/GerHynes/pen/YRwYzR

https://gk-hynes.github.io/fcc-survey-form/

#### Screenshot
https://res.cloudinary.com/gerhynes/image/upload/q_auto/v1541664543/Survey_form_screenshot_i9btbz.jpg

**Comment by ValeraS** [comment]
@GK-Hynes what test fails?
![image](https://user-images.githubusercontent.com/10867286/48188973-1391a100-e350-11e8-8161-48fa85998c72.png)

**Comment by GK-Hynes** [comment]
It's test 13.

I'm getting the message:

https://res.cloudinary.com/gerhynes/image/upload/v1541714561/failing_test_screenshot_wb9hic.png

13. Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute.
All your radio-buttons must have a value attribute : expected 20 to equal 18
AssertionError: All your radio-buttons must have a value attribute : expected 20 to equal 18
    at s.u (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:262:1134)
    at s.e.(anonymous function) [as equal] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:325:126)
    at Function.n.strictEqual (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:224:568)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:318122)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31608)
    at o.f.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31544)
    at m.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37114)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37976
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36426)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36495
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:35901)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36313
    at f (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:435937)

It works fine on mobile. 

https://res.cloudinary.com/gerhynes/image/upload/v1541714619/Screenshot_20181108-215709_ps2hnc.jpg

I've cleared the cache in case my browser was loading an earlier version.
