### ISSUE TITLE
Portfolio tests #7

### ISSUE THREAD

**Issue by joseph-mpo** [freeCodeCamp/testable-projects-fcc#721]
#### Issue Description

I have nav links and they a linked to the corresponding section of my page. Yet I get this error at test 7 for unknown reasons.

```
Cannot read property 'substr' of null
TypeError: Cannot read property 'substr' of null
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:330182
    at Array.filter (<anonymous>)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:330129)
    at O (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:326023)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:325811)
    at Generator.e.(anonymous function) [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:326202)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:84770)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:84980)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:85039
    at new Promise (<anonymous>)
```

#### Browser Information

* Browser Name, Version: Google Chrome, 70.0.3538.110
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/joseph-mpo/pen/BGeVdO?editors=1100
```

**Comment by joseph-mpo** [comment]
I had a link in the nav that did not contain an href attribute. I fixed it.
