### ISSUE TITLE
My pomodoro clock works properly but it doesn't pass the test. It says :  Timer has not reached 00:00.

### ISSUE THREAD

**Issue by HadiMohseni** [freeCodeCamp/testable-projects-fcc#888]
#### Issue Description
My pomodoro clock works properly but it doesn't pass the test.

 Link to Your Pen:
https://codepen.io/hdmohseni/pen/Rmbedv?editors=0010
 
 In timer section it says '_Error: Timer has not reached 00:00._' but it reaches to 00:00.
```
Can anyone help please?


#### Screenshot
#Technology Stack
1. You can use any mix of HTML, JavaScript, CSS, Bootstrap, SASS, React, Redux, and jQuery to complete this project. You should use a frontend framework (like React for example) because this section is about learning frontend frameworks. Additional technologies not listed above are not recommended and using them is at your own risk. We are looking at supporting other frontend frameworks like Angular and Vue, but they are not currently supported. We will accept and try to fix all issue reports that use the suggested technology stack for this project. Happy coding!
#Content
1. I can see an element with id="break-label" that contains a string (e.g. “Break Length”).
2. I can see an element with id="session-label" that contains a string (e.g. "Session Length”).
3. I can see two clickable elements with corresponding IDs: id="break-decrement" and id="session-decrement".
4. I can see two clickable elements with corresponding IDs: id="break-increment" and id="session-increment".
5. I can see an element, with corresponding id="break-length", which by default (on load) displays a value of 5.
6. I can see an element, with corresponding id="session-length", which by default displays a value of 25.
7. I can see an element, with corresponding id="timer-label", that contains a string indicating a session is initialized (e.g. "Session").
8. I can see an element with corresponding id="time-left". NOTE: Paused or running, the value in this field should always be displayed in mm:ss format (i.e. 25:00).
9. I can see a clickable element with corresponding id="start_stop".
10. I can see a clickable element with corresponding id="reset".
#Timer
1. When I click the element with the id of "reset", any running timer should be stopped, the value within id="break-length" should return to 5, the value within id="session-length" should return to 25, and the element with id="time-left" should reset to it's default state.
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
2. When I click the element with the id of "break-decrement", the value within id="break-length" decrements by a value of 1, and I can see the updated value.
3. When I click the element with the id of "break-increment", the value within id="break-length" increments by a value of 1, and I can see the updated value.
4. When I click the element with the id of "session-decrement", the value within id="session-length" decrements by a value of 1, and I can see the updated value.
5. When I click the element with the id of "session-increment", the value within id="session-length" increments by a value of 1, and I can see the updated value.
6. I should not be able to set a session or break length to <= 0.
7. I should not be able to set a session or break length to > 60.
8. When I first click the element with id="start_stop", the timer should begin running from the value currently displayed in id="session-length", even if the value has been incremented or decremented from the original value of 25.
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at u (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80067)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:87446)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31608)
    at o.f.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31544)
    at m.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37114)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37976
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36426)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36495
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:35901)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36313
9. If the timer is running, the element with the id of "time-left" should display the remaining time in mm:ss format (decrementing by a value of 1 and updating the display every 1000ms).
Cannot read property '2' of null
TypeError: Cannot read property '2' of null
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80101)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:87881)
    at O (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134369)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134157)
    at Generator.e.<computed> [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134548)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1055)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1265)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1324
    at new Promise (<anonymous>)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1206)
10. If the timer is running and I click the element with id="start_stop", the countdown should pause.
Cannot read property '2' of null
TypeError: Cannot read property '2' of null
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80101)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:88379)
    at O (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134369)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134157)
    at Generator.e.<computed> [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134548)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1055)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1265)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1324
    at new Promise (<anonymous>)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1206)
11. If the timer is paused and I click the element with id="start_stop", the countdown should resume running from the point at which it was paused.
Cannot read property '2' of null
TypeError: Cannot read property '2' of null
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80101)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:89107)
    at O (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134369)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134157)
    at Generator.e.<computed> [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:134548)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1055)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1265)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1324
    at new Promise (<anonymous>)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1206)
12. When a session countdown reaches zero (NOTE: timer MUST reach 00:00), and a new countdown begins, the element with the id of "timer-label" should display a string indicating a break has begun.
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
13. When a session countdown reaches zero (NOTE: timer MUST reach 00:00), a new break countdown should begin, counting down from the value currently displayed in the id="break-length" element.
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
14. When a break countdown reaches zero (NOTE: timer MUST reach 00:00), and a new countdown begins, the element with the id of "timer-label" should display a string indicating a session has begun.
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
15. When a break countdown reaches zero (NOTE: timer MUST reach 00:00), a new session countdown should begin, counting down from the value currently displayed in the id="session-length" element.
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
#Audio
1. When a countdown reaches zero (NOTE: timer MUST reach 00:00), a sound indicating that time is up should play. This should utilize an HTML5 <audio> tag and have a corresponding id="beep".
Timer has not reached 00:00.
Error: Timer has not reached 00:00.
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:80277
var t=this,a=arguments;return new Promise(function(n,s){var o=e.apply(t,a);function i(e){r(o,n,s,i,l,"next",e)}function l(e){r(o,n,s,i,l,"throw",e)}i(void 0)})
2. The audio element with id="beep" must be 1 second or longer.
3. The audio element with id of "beep" must stop playing and be rewound to the beginning when the element with the id of "reset" is clicked.

**Comment by HadiMohseni** [comment]
Label valid bug means my code is correct and it's a bug in the test suite?

**Comment by tbushman** [comment]
@HadiMohseni Yes. I can't see anything wrong with your code. Some others may see something I don't, however. Thanks for your patience!

**Comment by aaronmassey45** [comment]
There are various errors in your code. I tried playing around with a few of them and got some of the tests to pass. I suggest reviewing your code and looking for the errors. If you need some help just let me know!

**Comment by RandellDawson** [comment]
@HadiMohseni Did you post your code on the forum to see if anyone could help you figure out your issue?  That is always the best place to start.  They would steer you here if there is not something wrong with your code.

**Comment by thecodingaviator** [comment]
Related to #871 ?

**Comment by HadiMohseni** [comment]
> There are various errors in your code. I tried playing around with a few of them and got some of the tests to pass. I suggest reviewing your code and looking for the errors. If you need some help just let me know!
Cloud you please point out some of errors that I've made?
Thanks a lot.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
